# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='date_end',
            field=models.DateField(verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='date_start',
            field=models.DateField(verbose_name='date started'),
        ),
    ]
