# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safra', '0002_auto_20170201_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateField(verbose_name='date started')),
                ('date_end', models.DateField(verbose_name='date ended')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safra.Harvest')),
            ],
        ),
        migrations.CreateModel(
            name='UsedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safra.Product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='products',
            field=models.ManyToManyField(through='services.UsedProducts', to='safra.Product'),
        ),
    ]
